ALTER TABLE public.research_jobs
  ADD COLUMN IF NOT EXISTS plan_goal TEXT,
  ADD COLUMN IF NOT EXISTS plan_intro TEXT,
  ADD COLUMN IF NOT EXISTS plan_ready TEXT,
  ADD COLUMN IF NOT EXISTS awaiting_approval BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS thinking TEXT,
  ADD COLUMN IF NOT EXISTS unused_sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS needs_images BOOLEAN NOT NULL DEFAULT TRUE;